/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@bulmil/core';


interface BmBadgeProps {
  
  /** Color */
  color?: Components.BmBadge["color"]
  
  /** Position */
  position?: Components.BmBadge["position"]
  
  /** Is outlined */
  isOutlined?: Components.BmBadge["isOutlined"]
  
  /** Is light */
  isLight?: Components.BmBadge["isLight"]
}

interface BmBadgeEvents {
  
}

interface BmBadgeSlots {
  default: any
}
  
/* generated by Svelte v3.46.4 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let bm_badge;
	let current;
	const default_slot_template = /*#slots*/ ctx[7].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[6], null);

	return {
		c() {
			bm_badge = element("bm-badge");
			if (default_slot) default_slot.c();
			set_custom_element_data(bm_badge, "color", /*color*/ ctx[0]);
			set_custom_element_data(bm_badge, "position", /*position*/ ctx[1]);
			set_custom_element_data(bm_badge, "is-outlined", /*isOutlined*/ ctx[2]);
			set_custom_element_data(bm_badge, "is-light", /*isLight*/ ctx[3]);
		},
		m(target, anchor) {
			insert(target, bm_badge, anchor);

			if (default_slot) {
				default_slot.m(bm_badge, null);
			}

			/*bm_badge_binding*/ ctx[8](bm_badge);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 64)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[6],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[6])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[6], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*color*/ 1) {
				set_custom_element_data(bm_badge, "color", /*color*/ ctx[0]);
			}

			if (!current || dirty & /*position*/ 2) {
				set_custom_element_data(bm_badge, "position", /*position*/ ctx[1]);
			}

			if (!current || dirty & /*isOutlined*/ 4) {
				set_custom_element_data(bm_badge, "is-outlined", /*isOutlined*/ ctx[2]);
			}

			if (!current || dirty & /*isLight*/ 8) {
				set_custom_element_data(bm_badge, "is-light", /*isLight*/ ctx[3]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(bm_badge);
			if (default_slot) default_slot.d(detaching);
			/*bm_badge_binding*/ ctx[8](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { color = undefined } = $$props;
	let { position = undefined } = $$props;
	let { isOutlined = undefined } = $$props;
	let { isLight = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(4, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function bm_badge_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(4, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('color' in $$props) $$invalidate(0, color = $$props.color);
		if ('position' in $$props) $$invalidate(1, position = $$props.position);
		if ('isOutlined' in $$props) $$invalidate(2, isOutlined = $$props.isOutlined);
		if ('isLight' in $$props) $$invalidate(3, isLight = $$props.isLight);
		if ('$$scope' in $$props) $$invalidate(6, $$scope = $$props.$$scope);
	};

	return [
		color,
		position,
		isOutlined,
		isLight,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		bm_badge_binding
	];
}

class BmBadge extends SvelteComponent {
  $$prop_def: BmBadgeProps;
  $$events_def: BmBadgeEvents;
  $$slot_def: BmBadgeSlots;

  $on<K extends keyof BmBadgeEvents>(type: K, callback: (e: BmBadgeEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<BmBadgeProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			color: 0,
			position: 1,
			isOutlined: 2,
			isLight: 3,
			getWebComponent: 5
		});
	}

	get color() {
		return this.$$.ctx[0];
	}

	set color(color) {
		this.$$set({ color });
		flush();
	}

	get position() {
		return this.$$.ctx[1];
	}

	set position(position) {
		this.$$set({ position });
		flush();
	}

	get isOutlined() {
		return this.$$.ctx[2];
	}

	set isOutlined(isOutlined) {
		this.$$set({ isOutlined });
		flush();
	}

	get isLight() {
		return this.$$.ctx[3];
	}

	set isLight(isLight) {
		this.$$set({ isLight });
		flush();
	}

	get getWebComponent(): HTMLBmBadgeElement | undefined {
		return this.$$.ctx[5];
	}
}

export default BmBadge;