/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@bulmil/core';


interface BmContainerProps {
  
  /** Container breakpoint */
  breakpoint?: Components.BmContainer["breakpoint"]
  
  /** Fluid container */
  isFluid?: Components.BmContainer["isFluid"]
}

interface BmContainerEvents {
  
}

interface BmContainerSlots {
  default: any
}
  
/* generated by Svelte v3.46.4 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let bm_container;
	let current;
	const default_slot_template = /*#slots*/ ctx[5].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[4], null);

	return {
		c() {
			bm_container = element("bm-container");
			if (default_slot) default_slot.c();
			set_custom_element_data(bm_container, "breakpoint", /*breakpoint*/ ctx[0]);
			set_custom_element_data(bm_container, "is-fluid", /*isFluid*/ ctx[1]);
		},
		m(target, anchor) {
			insert(target, bm_container, anchor);

			if (default_slot) {
				default_slot.m(bm_container, null);
			}

			/*bm_container_binding*/ ctx[6](bm_container);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 16)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[4],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[4])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[4], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*breakpoint*/ 1) {
				set_custom_element_data(bm_container, "breakpoint", /*breakpoint*/ ctx[0]);
			}

			if (!current || dirty & /*isFluid*/ 2) {
				set_custom_element_data(bm_container, "is-fluid", /*isFluid*/ ctx[1]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(bm_container);
			if (default_slot) default_slot.d(detaching);
			/*bm_container_binding*/ ctx[6](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { breakpoint = undefined } = $$props;
	let { isFluid = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(2, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function bm_container_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(2, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('breakpoint' in $$props) $$invalidate(0, breakpoint = $$props.breakpoint);
		if ('isFluid' in $$props) $$invalidate(1, isFluid = $$props.isFluid);
		if ('$$scope' in $$props) $$invalidate(4, $$scope = $$props.$$scope);
	};

	return [
		breakpoint,
		isFluid,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		bm_container_binding
	];
}

class BmContainer extends SvelteComponent {
  $$prop_def: BmContainerProps;
  $$events_def: BmContainerEvents;
  $$slot_def: BmContainerSlots;

  $on<K extends keyof BmContainerEvents>(type: K, callback: (e: BmContainerEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<BmContainerProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			breakpoint: 0,
			isFluid: 1,
			getWebComponent: 3
		});
	}

	get breakpoint() {
		return this.$$.ctx[0];
	}

	set breakpoint(breakpoint) {
		this.$$set({ breakpoint });
		flush();
	}

	get isFluid() {
		return this.$$.ctx[1];
	}

	set isFluid(isFluid) {
		this.$$set({ isFluid });
		flush();
	}

	get getWebComponent(): HTMLBmContainerElement | undefined {
		return this.$$.ctx[3];
	}
}

export default BmContainer;