/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@bulmil/core';


interface BmSelectProps {
  
  /** Control classes */
  controlClass?: Components.BmSelect["controlClass"]
  
  /** Value */
  value?: Components.BmSelect["value"]
  
  /** Color */
  color?: Components.BmSelect["color"]
  
  /** Size */
  size?: Components.BmSelect["size"]
  
  /** State */
  state?: Components.BmSelect["state"]
  
  /** Allows multiple selection */
  isMultiple?: Components.BmSelect["isMultiple"]
  
  /** Loading state */
  isLoading?: Components.BmSelect["isLoading"]
  
  /** Rounded */
  isRounded?: Components.BmSelect["isRounded"]
  
  /** Icon */
  icon?: Components.BmSelect["icon"]
}

interface BmSelectEvents {
  
}

interface BmSelectSlots {
  default: any
}
  
/* generated by Svelte v3.24.1 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount } from "svelte";

function create_fragment(ctx) {
	let bm_select;
	let current;
	const default_slot_template = /*$$slots*/ ctx[12].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[11], null);

	return {
		c() {
			bm_select = element("bm-select");
			if (default_slot) default_slot.c();
			set_custom_element_data(bm_select, "control-class", /*controlClass*/ ctx[0]);
			set_custom_element_data(bm_select, "value", /*value*/ ctx[1]);
			set_custom_element_data(bm_select, "color", /*color*/ ctx[2]);
			set_custom_element_data(bm_select, "size", /*size*/ ctx[3]);
			set_custom_element_data(bm_select, "state", /*state*/ ctx[4]);
			set_custom_element_data(bm_select, "is-multiple", /*isMultiple*/ ctx[5]);
			set_custom_element_data(bm_select, "is-loading", /*isLoading*/ ctx[6]);
			set_custom_element_data(bm_select, "is-rounded", /*isRounded*/ ctx[7]);
			set_custom_element_data(bm_select, "icon", /*icon*/ ctx[8]);
		},
		m(target, anchor) {
			insert(target, bm_select, anchor);

			if (default_slot) {
				default_slot.m(bm_select, null);
			}

			/*bm_select_binding*/ ctx[13](bm_select);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 2048) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[11], dirty, null, null);
				}
			}

			if (!current || dirty & /*controlClass*/ 1) {
				set_custom_element_data(bm_select, "control-class", /*controlClass*/ ctx[0]);
			}

			if (!current || dirty & /*value*/ 2) {
				set_custom_element_data(bm_select, "value", /*value*/ ctx[1]);
			}

			if (!current || dirty & /*color*/ 4) {
				set_custom_element_data(bm_select, "color", /*color*/ ctx[2]);
			}

			if (!current || dirty & /*size*/ 8) {
				set_custom_element_data(bm_select, "size", /*size*/ ctx[3]);
			}

			if (!current || dirty & /*state*/ 16) {
				set_custom_element_data(bm_select, "state", /*state*/ ctx[4]);
			}

			if (!current || dirty & /*isMultiple*/ 32) {
				set_custom_element_data(bm_select, "is-multiple", /*isMultiple*/ ctx[5]);
			}

			if (!current || dirty & /*isLoading*/ 64) {
				set_custom_element_data(bm_select, "is-loading", /*isLoading*/ ctx[6]);
			}

			if (!current || dirty & /*isRounded*/ 128) {
				set_custom_element_data(bm_select, "is-rounded", /*isRounded*/ ctx[7]);
			}

			if (!current || dirty & /*icon*/ 256) {
				set_custom_element_data(bm_select, "icon", /*icon*/ ctx[8]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(bm_select);
			if (default_slot) default_slot.d(detaching);
			/*bm_select_binding*/ ctx[13](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { controlClass = undefined } = $$props;
	let { value = undefined } = $$props;
	let { color = undefined } = $$props;
	let { size = undefined } = $$props;
	let { state = undefined } = $$props;
	let { isMultiple = undefined } = $$props;
	let { isLoading = undefined } = $$props;
	let { isRounded = undefined } = $$props;
	let { icon = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(9, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	let { $$slots = {}, $$scope } = $$props;

	function bm_select_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			__ref = $$value;
			$$invalidate(9, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ("controlClass" in $$props) $$invalidate(0, controlClass = $$props.controlClass);
		if ("value" in $$props) $$invalidate(1, value = $$props.value);
		if ("color" in $$props) $$invalidate(2, color = $$props.color);
		if ("size" in $$props) $$invalidate(3, size = $$props.size);
		if ("state" in $$props) $$invalidate(4, state = $$props.state);
		if ("isMultiple" in $$props) $$invalidate(5, isMultiple = $$props.isMultiple);
		if ("isLoading" in $$props) $$invalidate(6, isLoading = $$props.isLoading);
		if ("isRounded" in $$props) $$invalidate(7, isRounded = $$props.isRounded);
		if ("icon" in $$props) $$invalidate(8, icon = $$props.icon);
		if ("$$scope" in $$props) $$invalidate(11, $$scope = $$props.$$scope);
	};

	return [
		controlClass,
		value,
		color,
		size,
		state,
		isMultiple,
		isLoading,
		isRounded,
		icon,
		__ref,
		getWebComponent,
		$$scope,
		$$slots,
		bm_select_binding
	];
}

class BmSelect extends SvelteComponent {
  $$prop_def: BmSelectProps;
  $$events_def: BmSelectEvents;
  $$slot_def: BmSelectSlots;

  $on<K extends keyof BmSelectEvents>(type: K, callback: (e: BmSelectEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<BmSelectProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			controlClass: 0,
			value: 1,
			color: 2,
			size: 3,
			state: 4,
			isMultiple: 5,
			isLoading: 6,
			isRounded: 7,
			icon: 8,
			getWebComponent: 10
		});
	}

	get controlClass() {
		return this.$$.ctx[0];
	}

	set controlClass(controlClass) {
		this.$set({ controlClass });
		flush();
	}

	get value() {
		return this.$$.ctx[1];
	}

	set value(value) {
		this.$set({ value });
		flush();
	}

	get color() {
		return this.$$.ctx[2];
	}

	set color(color) {
		this.$set({ color });
		flush();
	}

	get size() {
		return this.$$.ctx[3];
	}

	set size(size) {
		this.$set({ size });
		flush();
	}

	get state() {
		return this.$$.ctx[4];
	}

	set state(state) {
		this.$set({ state });
		flush();
	}

	get isMultiple() {
		return this.$$.ctx[5];
	}

	set isMultiple(isMultiple) {
		this.$set({ isMultiple });
		flush();
	}

	get isLoading() {
		return this.$$.ctx[6];
	}

	set isLoading(isLoading) {
		this.$set({ isLoading });
		flush();
	}

	get isRounded() {
		return this.$$.ctx[7];
	}

	set isRounded(isRounded) {
		this.$set({ isRounded });
		flush();
	}

	get icon() {
		return this.$$.ctx[8];
	}

	set icon(icon) {
		this.$set({ icon });
		flush();
	}

	get getWebComponent(): HTMLBmSelectElement | undefined {
		return this.$$.ctx[10];
	}
}

export default BmSelect;