/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from './stencil.core';


export namespace Components {
  interface BButton {
    'disabled': boolean;
    'type': 'is-primary' | '';
  }
  interface BInput {
    'name': string;
    'required': boolean;
    'type': string;
    'value': string | number;
  }
}

declare global {


  interface HTMLBButtonElement extends Components.BButton, HTMLStencilElement {}
  var HTMLBButtonElement: {
    prototype: HTMLBButtonElement;
    new (): HTMLBButtonElement;
  };

  interface HTMLBInputElement extends Components.BInput, HTMLStencilElement {}
  var HTMLBInputElement: {
    prototype: HTMLBInputElement;
    new (): HTMLBInputElement;
  };
  interface HTMLElementTagNameMap {
    'b-button': HTMLBButtonElement;
    'b-input': HTMLBInputElement;
  }
}

declare namespace LocalJSX {
  interface BButton extends JSXBase.HTMLAttributes<HTMLBButtonElement> {
    'disabled'?: boolean;
    'onClicked'?: (event: CustomEvent<any>) => void;
    'type'?: 'is-primary' | '';
  }
  interface BInput extends JSXBase.HTMLAttributes<HTMLBInputElement> {
    'name'?: string;
    'required'?: boolean;
    'type'?: string;
    'value'?: string | number;
  }

  interface IntrinsicElements {
    'b-button': BButton;
    'b-input': BInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


